//
//  @file Language.cpp
//  @author Sergii Oryshchenko <sergii.orishchenko@gmail.com>
//  @see https://github.com/os-v/UniProInstaller/
//
//  Created on 23.10.20.
//  Copyright 2020 Sergii Oryshchenko. All rights reserved.
//

#include "Language.h"
#include <string.h>

const char *GLanguageEnglish[] = {
	"Install",
	"Uninstall",
	"OK",
	"Yes",
	"No",
	"Advanced",
	"Back",
	"Next",
	"Cancel",
	"Accept",
	"Continue",
	"Finish",
	"Finished",
	"Welcome to the %s installer",
	"Enter additional configuration",
	"Advanced configuration mode",
	"Please configure settings",
	"License Agreement",
	"Please read and accept license agreement",
	"Typical",
	"Configuration type",
	"Please select installation type",
	"Installation has been finished. %s",
	"%s has been reinstalled. %s",
	"%s has been updated. %s",
	"%s has been removed.",
	"Please close installer to start using %s.",
	"Preparing",
	"Installation",
	"Re-installation",
	"Updating",
	"Uninstalling",
	"Please wait while installing %s.",
	"Please wait while re-installing %s.",
	"Please wait while updating %s.",
	"Please wait while removing %s.",
	"Click Continue button to start.",
	"This installer is ready to install %s to your computer. %s",
	"This installer is ready to reinstall %s to your computer. %s",
	"This installer is ready to update %s to your computer. %s",
	"This installer is ready to uninstall %s from your computer. %s",
	"Ready to start installation of %s.",
	"Ready to re-install %s.",
	"Ready to update %s.",
	"Ready to remove %s.",
	"Click next to continue.",
	"This installer will update %s to version %s on your computer. %s",
	"This installer will reinstall %s version %s on your computer. %s",
	"This installer will install %s version %s on your computer. %s",
	"Or click Uninstall button to uninstall %s v%s",
	"Cancel confirmation",
	"Do you really want to abort installation?",
	"Preparing ...",
	"Extracting files ...",
	"Copying Files ...",
	"Removing Files ...",
	"Registering components ...",
	"Configuring ...",
	"Finalizing ...",
	"Command execution failed.",
	"Please Select Language",
	"Unable to remove previous version.",
};

const char *GLanguageGermany[] = {
	"Installieren",
	"Deinstallieren",
	"OK",
	"Ja",
	"Nein",
	"Advanced",
	"&Zurück",
	"Nächster",
	"Stornieren",
	"Akzeptieren",
	"Fortsetzen",
	"Fertig",
	"Fertig",
	"Willkommen beim %s Installer",
	"Geben Sie eine zusätzliche konfiguration ein",
	"Erweiterter Konfigurationsmodus",
	"Bitte Einstellungen konfigurieren",
	"Lizenzvereinbarung",
	"Bitte lesen und akzeptieren Sie die Lizenzvereinbarung",
	"Typisch",
	"Konfigurationstyp",
	"Bitte Installationsart auswählen",
	"Die Installation wurde abgeschlossen. %s",
	"%s wurde neu installiert. %s",
	"%s wurde aktualisiert. %s",
	"%s wurde entfernt.",
	"Bitte schließen Sie das Installationsprogramm, um %s zu verwenden.",
	"Vorbereiten",
	"Installation",
	"Neuinstallation",
	"Aktualisierung",
	"Deinstallation",
	"Bitte warten Sie, während Sie %s installieren.",
	"Bitte warten Sie, während Sie %s neu installieren.",
	"Bitte warten Sie, während Sie %s aktualisieren.",
	"Bitte warten Sie, während Sie %s entfernen.",
	"Klicken Sie zum Starten auf die Schaltfläche Weiter.",
	"Dieses Installationsprogramm ist bereit, %s auf Ihrem Computer zu installieren. %s",
	"Dieses Installationsprogramm ist bereit, %s auf Ihrem Computer neu zu installieren. %s",
	"Dieses Installationsprogramm ist bereit, %s auf Ihren Computer zu aktualisieren. %s",
	"Dieses Installationsprogramm ist bereit, %s von Ihrem Computer zu deinstallieren. %s",
	"Bereit zum Starten der Installation von %s.",
	"Bereit zur Neuinstallation von %s.",
	"Bereit zum Aktualisieren von %s.",
	"Bereit zum Entfernen von %s.",
	"Klicke weiter um fortzufahren.",
	"Dieses Installationsprogramm aktualisiert %s auf Version %s auf Ihrem Computer. %s",
	"Dieses Installationsprogramm installiert %s Version %s auf Ihrem Computer neu. %s",
	"Dieses Installationsprogramm installiert %s Version %s auf Ihrem Computer. %s",
	"Oder klicken Sie auf die Schaltfläche Deinstallieren, um %s v%s zu deinstallieren",
	"Bestätigung abbrechen",
	"Möchten Sie die Installation wirklich abbrechen?",
	"Vorbereiten ...",
	"Entpacke Dateien ...",
	"Dateien kopieren ...",
	"Dateien entfernen ...",
	"Komponenten registrieren ...",
	"Konfigurieren ...",
	"Finalisieren ...",
	"Befehlsausführung fehlgeschlagen.",
	"Bitte Sprache auswählen",
	"Vorherige Version kann nicht entfernt werden.",
};

const char *GLanguageFrench[] = {
	"Installer",
	"Désinstaller",
	"D'ACCORD",
	"Oui",
	"Non",
	"Avancée",
	"Retour",
	"Suivant",
	"Annuler",
	"J'accepte",
	"Continuer",
	"Terminer",
	"Fini",
	"Bienvenue dans l'installateur %s",
	"Entrez une configuration supplémentaire",
	"Mode de configuration avancée",
	"Veuillez configurer les paramètres",
	"Accord de licence",
	"Veuillez lire et accepter le contrat de licence",
	"Typique",
	"Type de configuration",
	"Veuillez sélectionner le type d'installation",
	"L'installation est terminée. %s",
	"%s a été réinstallé. %s",
	"%s a été mis à jour. %s",
	"%s a été supprimé.",
	"Veuillez fermer le programme d'installation pour commencer à utiliser %s.",
	"En train de préparer",
	"Installation",
	"Réinstallation",
	"Mise à jour",
	"Désinstallation",
	"Veuillez patienter pendant l'installation de %s.",
	"Veuillez patienter pendant la réinstallation de %s.",
	"Veuillez patienter pendant la mise à jour de %s.",
	"Veuillez patienter pendant la suppression de %s.",
	"Cliquez sur le bouton Continuer pour commencer.",
	"Ce programme d'installation est prêt à installer %s sur votre ordinateur. %s",
	"Ce programme d'installation est prêt à réinstaller %s sur votre ordinateur. %s",
	"Ce programme d'installation est prêt à mettre à jour %s sur votre ordinateur. %s",
	"Ce programme d'installation est prêt à désinstaller %s de votre ordinateur. %s",
	"Prêt à démarrer l'installation de %s.",
	"Prêt à réinstaller %s.",
	"Prêt à mettre à jour %s.",
	"Prêt à supprimer %s.",
	"Cliquer sur Suivant pour continuer.",
	"Ce programme d'installation mettra à jour %s vers la version %s sur votre ordinateur. %s",
	"Ce programme d'installation va réinstaller %s version %s sur votre ordinateur. %s",
	"Ce programme d'installation installera %s version %s sur votre ordinateur. %s",
	"Ou cliquez sur le bouton Désinstaller pour désinstaller %s v%s",
	"Annuler la confirmation",
	"Voulez-vous vraiment abandonner l'installation?",
	"En train de préparer ...",
	"Extraction des fichiers ...",
	"Copie de fichiers ...",
	"Suppression de fichiers ...",
	"Enregistrement des composants ...",
	"Configuration ...",
	"Finalisation ...",
	"L'exécution de la commande a échoué.",
	"Veuillez sélectionner la langue",
	"Impossible de supprimer la version précédente.",
};

const char *GLanguageItalian[] = {
	"Installare",
	"Disinstalla",
	"OK",
	"Sì",
	"No",
	"Avanzate",
	"Indietro",
	"Il prossimo",
	"Annulla",
	"Accettare",
	"Continua",
	"Finire",
	"Finito",
	"Benvenuto nel programma di installazione %s",
	"Immettere una configurazione aggiuntiva",
	"Modalità di configurazione avanzata",
	"Configura le impostazioni",
	"Contratto di licenza",
	"Leggere e accettare il contratto di licenza",
	"Tipico",
	"Tipo di configurazione",
	"Seleziona il tipo di installazione",
	"L'installazione è stata completata. %s",
	"%s è stato reinstallato. %s",
	"%s è stato aggiornato. %s",
	"%s è stato rimosso.",
	"Chiudi il programma di installazione per iniziare a utilizzare %s.",
	"Preparazione",
	"Installazione",
	"Reinstallazione",
	"In aggiornamento",
	"Disinstallazione",
	"Attendi durante l'installazione di %s.",
	"Attendi durante la reinstallazione di %s.",
	"Attendi durante l'aggiornamento di %s.",
	"Attendi durante la rimozione di %s.",
	"Fare clic sul pulsante Continua per iniziare.",
	"Questo programma di installazione è pronto per installare %s sul tuo computer. %s",
	"Questo programma di installazione è pronto per reinstallare %s sul tuo computer. %s",
	"Questo programma di installazione è pronto per aggiornare %s sul tuo computer. %s",
	"Questo programma di installazione è pronto per disinstallare %s dal tuo computer. %s",
	"Pronto per avviare l'installazione di %s.",
	"Pronto per reinstallare %s.",
	"Pronto per aggiornare %s.",
	"Pronto per rimuovere %s.",
	"Fare clic su Avanti per continuare.",
	"Questo programma di installazione aggiornerà %s alla versione %s sul tuo computer. %s",
	"Questo programma di installazione reinstallerà %s versione %s sul tuo computer. %s",
	"Questo programma di installazione installerà %s versione %s sul tuo computer. %s",
	"Oppure fai clic sul pulsante Disinstalla per disinstallare %s v%s",
	"Annulla conferma",
	"Vuoi davvero interrompere l'installazione?",
	"Preparazione ...",
	"Estrazione file in corso ...",
	"Copia file ...",
	"Rimozione dei file ...",
	"Registrazione dei componenti ...",
	"Configurazione ...",
	"Finalizzazione ...",
	"Esecuzione del comando non riuscita.",
	"Seleziona la lingua",
	"Impossibile rimuovere la versione precedente.",
};

const char *GLanguageSpanish[] = {
	"Instalar en pc",
	"Desinstalar",
	"OKAY",
	"Si",
	"No",
	"Avanzado",
	"Atrás",
	"Próximo",
	"Cancelar",
	"Aceptar",
	"Seguir",
	"Terminar",
	"Terminado",
	"Bienvenido al instalador de %s",
	"Ingrese configuración adicional",
	"Modo de configuración avanzada",
	"Configure los ajustes",
	"Acuerdo de licencia",
	"Lea y acepte el acuerdo de licencia",
	"Típico",
	"Tipo de configuración",
	"Seleccione el tipo de instalación",
	"La instalación ha finalizado. %s",
	"%s ha sido reinstalado. %s",
	"%s ha sido actualizado. %s",
	"%s ha sido eliminado.",
	"Cierre el instalador para comenzar a usar %s.",
	"Preparando",
	"Instalación",
	"Reinstalación",
	"Actualizando",
	"Desinstalando",
	"Espere mientras instala %s.",
	"Espere mientras reinstala %s.",
	"Espere mientras actualiza %s.",
	"Espere mientras elimina %s.",
	"Haga clic en el botón Continuar para comenzar",
	"Este instalador está listo para instalar %s en su computadora. %s",
	"Este instalador está listo para reinstalar %s en su computadora. %s",
	"Este instalador está listo para actualizar %s en su computadora. %s",
	"Este instalador está listo para desinstalar %s de su computadora. %s",
	"Listo para iniciar la instalación de %s.",
	"Listo para reinstalar %s.",
	"Listo para actualizar %s.",
	"Listo para eliminar %s.",
	"Haga clic en Siguiente para continuar.",
	"Este instalador actualizará %s a la versión %s en su computadora. %s",
	"Este instalador reinstalará %s versión %s en su computadora. %s",
	"Este instalador instalará %s versión %s en su computadora. %s",
	"O haga clic en el botón Desinstalar para desinstalar %s v%s",
	"Cancelar confirmación",
	"¿Realmente desea cancelar la instalación?",
	"Preparando ...",
	"Extrayendo archivos ...",
	"Copiando documentos ...",
	"Eliminando archivos ...",
	"Registrando componentes ...",
	"Configurando ...",
	"Finalizando ...",
	"Error en la ejecución del comando",
	"Seleccione el idioma",
	"No se puede eliminar la versión anterior.",
};

const char *GLanguagePortuguese[] = {
	"Instalar",
	"Desinstalar",
	"ESTÁ BEM",
	"Sim",
	"Não",
	"Avançado",
	"Costas",
	"Próximo",
	"Cancelar",
	"Aceitar",
	"Continuar",
	"Terminar",
	"Acabado",
	"Bem-vindo ao instalador %s",
	"Insira a configuração adicional",
	"Modo de configuração avançada",
	"Defina as configurações",
	"Contrato de Licença",
	"Leia e aceite o contrato de licença",
	"Típica",
	"Tipo de configuração",
	"Selecione o tipo de instalação",
	"A instalação foi concluída. %s",
	"%s foi reinstalado. %s",
	"%s foi atualizado. %s",
	"%s foi removido.",
	"Feche o instalador para começar a usar %s.",
	"Preparando",
	"Instalação",
	"Reinstalação",
	"Atualizando",
	"Desinstalando",
	"Aguarde enquanto instala %s.",
	"Por favor, espere enquanto reinstalando %s.",
	"Por favor, espere enquanto atualiza %s.",
	"Por favor, espere enquanto remove %s.",
	"Clique no botão Continuar para iniciar.",
	"Este instalador está pronto para instalar %s no seu computador. %s",
	"Este instalador está pronto para reinstalar %s no seu computador. %s",
	"Este instalador está pronto para atualizar %s para o seu computador. %s",
	"Este instalador está pronto para desinstalar %s do seu computador. %s",
	"Pronto para iniciar a instalação de %s.",
	"Pronto para reinstalar %s.",
	"Pronto para atualizar %s.",
	"Pronto para remover %s.",
	"Clique em próximo para continuar.",
	"Este instalador irá atualizar %s para a versão %s no seu computador. %s",
	"Este instalador irá reinstalar %s versão %s no seu computador. %s",
	"Este instalador irá instalar %s versão %s no seu computador. %s",
	"Ou clique no botão Desinstalar para desinstalar %s v%s",
	"Cancelar confirmação",
	"Você realmente deseja abortar a instalação?",
	"Preparando ...",
	"Extraindo arquivos ...",
	"Copiando arquivos ...",
	"Removendo arquivos ...",
	"Registrando componentes ...",
	"Configurando ...",
	"Finalizando ...",
	"Falha na execução do comando.",
	"Selecione o idioma",
	"Incapaz de remover a versão anterior.",
};

const char *GLanguageRussian[] = {
	"Установить",
	"Удалить",
	"ОК",
	"Да",
	"Нет",
	"Дополнительно",
	"Назад",
	"Далее",
	"Отмена",
	"Принять",
	"Далее",
	"Закрыть",
	"Законченный",
	"Добро пожаловать в установщик %s",
	"Введите дополнительную конфигурацию",
	"Режим расширенной конфигурации",
	"Пожалуйста, настройте параметры",
	"Лицензионное соглашение",
	"Прочтите и примите лицензионное соглашение",
	"Типичный",
	"Тип конфигурации",
	"Выберите тип установки",
	"Установка завершена. %s",
	"%s был переустановлен. %s",
	"%s обновлен. %s",
	"%s удален.",
	"Закройте программу установки, чтобы начать использовать %s.",
	"Подготовка",
	"Установка",
	"Повторная установка",
	"Обновление",
	"Удаление",
	"Подождите, пока устанавливаете %s.",
	"Подождите, пока переустанавливаете %s.",
	"Подождите, пока обновляется %s.",
	"Подождите, пока удалит %s.",
	"Нажмите кнопку Продолжить, чтобы начать.",
	"Этот установщик готов установить %s на ваш компьютер. %s",
	"Этот установщик готов переустановить %s на ваш компьютер. %s",
	"Эта программа установки готова обновить %s на вашем компьютере. %s",
	"Эта программа установки готова удалить %s с вашего компьютера. %s",
	"Готов к установке %s.",
	"Готов к переустановке %s.",
	"Готов обновить %s.",
	"Готов удалить %s.",
	"Нажмите Далее, чтобы продолжить.",
	"Этот установщик обновит %s до версии %s на вашем компьютере. %s",
	"Этот установщик переустановит %s версию %s на ваш компьютер. %s",
	"Этот установщик установит на ваш компьютер %s версию %s. %s",
	"Или нажмите кнопку Удалить, чтобы удалить %s v %s",
	"Отменить подтверждение",
	"Вы действительно хотите прервать установку?",
	"Готовим ...",
	"Извлечения файлов ...",
	"Копирование файлов ...",
	"Удаление файлов ...",
	"Регистрация компонентов ...",
	"Настройка ...",
	"Завершение ...",
	"Ошибка выполнения команды.",
	"Пожалуйста, выберите язык",
	"Невозможно удалить предыдущую версию.",
};

const char *GLanguageJapanese[] = {
	"インストール",
	"アンインストール",
	"OK",
	"はい",
	"番号",
	"上級",
	"バック",
	"次",
	"キャンセル",
	"受け入れる",
	"継続する",
	"終了",
	"終了",
	"%s インストーラーへようこそ",
	"追加の構成を入力します",
	"詳細設定モード",
	"設定してください",
	"ライセンス契約",
	"使用許諾契約を読んで同意してください",
	"典型的な",
	"構成タイプ",
	"インストールタイプを選択してください",
	"インストールが完了しました. %s",
	"%s が再インストールされました. %s",
	"%s が更新されました. %s",
	"%s は削除されました.",
	"インストーラーを閉じて %s の使用を開始してください.",
	"準備",
	"インスタレーション",
	"再インストール",
	"更新中",
	"アンインストール",
	"%s をインストールするまでお待ちください.",
	"%s を再インストールするまでお待ちください.",
	"%s を更新するまでお待ちください.",
	"%s を削除するまでお待ちください.",
	"続行ボタンをクリックして開始してください.",
	"このインストーラーは %s をコンピューターにインストールする準備ができています. %s",
	"このインストーラーは, %s をコンピューターに再インストールする準備ができています. %s",
	"このインストーラーは, %s をコンピューターに更新する準備ができています. %s",
	"このインストーラーは,コンピューターから %s をアンインストールする準備ができています. %s",
	"%s のインストールを開始する準備ができました.",
	"%s を再インストールする準備ができました.",
	"%s を更新する準備ができました.",
	"%s を削除する準備ができました.",
	"次へをクリックして続行してください.",
	"このインストーラーは,コンピューターの %s をバージョン %s に更新します. %s",
	"このインストーラーは %s バージョン %s をコンピューターに再インストールします. %s",
	"このインストーラーは %s バージョン %s をコンピューターにインストールします. %s",
	"または,[アンインストール]ボタンをクリックして %s v%s をアンインストールします",
	"確認をキャンセル",
	"本当にインストールを中止しますか？",
	"準備 ...",
	"ファイルの抽出 ...",
	"ファイルのコピー...",
	"ファイルを削除しています...",
	"コンポーネントの登録...",
	"構成中...",
	"ファイナライズ...",
	"コマンドの実行に失敗しました.",
	"言語を選択してください",
	"以前のバージョンを削除できません.",
};

const char *GLanguageKorean[] = {
	"설치",
	"제거",
	"확인",
	"예",
	"아니",
	"많은",
	"뒤",
	"다음",
	"취소",
	"동의하기",
	"계속하다",
	"끝",
	"끝마친",
	"%s 설치 프로그램에 오신 것을 환영합니다",
	"추가 구성 입력",
	"고급 구성 모드",
	"설정을 구성하십시오",
	"라이센스 계약",
	"라이센스 계약을 읽고 동의하십시오",
	"전형적인",
	"구성 유형",
	"설치 유형을 선택하십시오",
	"설치가 완료되었습니다. %s",
	"%s 이 (가) 다시 설치되었습니다. %s",
	"%s 이 (가) 업데이트되었습니다. %s",
	"%s 이 (가) 제거되었습니다.",
	"%s 사용을 시작하려면 설치 프로그램을 닫으십시오.",
	"준비 중",
	"설치",
	"재설치",
	"업데이트",
	"제거",
	"%s 을 (를) 설치하는 동안 잠시 기다려주십시오.",
	"%s 을 (를) 재설치하는 동안 잠시 기다려주십시오.",
	"%s 을 (를) 업데이트하는 동안 잠시 기다려주십시오.",
	"%s 을 (를) 제거하는 동안 잠시 기다려주십시오.",
	"시작하려면 계속 버튼을 클릭하십시오.",
	"이 설치 프로그램은 %s 을 (를) 컴퓨터에 설치할 준비가되었습니다. %s",
	"이 설치 프로그램은 %s 을 (를) 컴퓨터에 다시 설치할 준비가되었습니다. %s",
	"이 설치 프로그램이 %s 을 (를) 컴퓨터로 업데이트 할 준비가되었습니다. %s",
	"이 설치 프로그램은 컴퓨터에서 %s 을 (를) 제거 할 준비가되었습니다. %s",
	"%s 설치를 시작할 준비가되었습니다.",
	"%s 을 (를) 재설치 할 준비가되었습니다.",
	"%s 을 (를) 업데이트 할 준비가되었습니다.",
	"%s 제거 준비 완료.",
	"계속하려면 다음을 클릭하십시오.",
	"이 설치 프로그램은 %s 을 컴퓨터의 %s 버전으로 업데이트합니다. %s",
	"이 설치 프로그램은 %s 버전 %s 을 (를) 컴퓨터에 다시 설치합니다. %s",
	"이 설치 프로그램은 %s 버전 %s 을 (를) 컴퓨터에 설치합니다. %s",
	"또는 제거 버튼을 클릭하여 %s v%s 제거",
	"확인 취소",
	"정말 설치를 중단 하시겠습니까?",
	"준비 중 ...",
	"파일 추출 중 ...",
	"파일 복사 중 ...",
	"파일 제거 중 ...",
	"구성 요소 등록 중 ...",
	"구성 중 ...",
	"완료 중 ...",
	"명령 실행에 실패했습니다.",
	"언어를 선택하십시오",
	"이전 버전을 제거 할 수 없습니다.",
};

const char *GLanguageChinese[] = {
	"安装",
	"卸载",
	"好",
	"是",
	"没有",
	"高级",
	"背部",
	"下一个",
	"取消",
	"接受",
	"继续",
	"完",
	"完成",
	"欢迎使用 %s 安装程序",
	"输入其他配置",
	"高级配置模式",
	"请配置设置",
	"许可协议",
	"请阅读并接受许可协议",
	"典型",
	"配置类型",
	"请选择安装类型",
	"安装已完成. %s",
	"%s 已重新安装. %s",
	"%s 已更新. %s",
	"%s 已被删除.",
	"请关闭安装程序以开始使用 %s.",
	"准备中",
	"安装",
	"重新安装",
	"正在更新",
	"卸载",
	"请等待 %s 的安装.",
	"请稍候，重新安装 %s.",
	"请稍候，正在更新 %s.",
	"请稍候，正在删除 %s.",
	"单击继续按钮开始.",
	"此安装程序已准备就绪，可以将 %s 安装到您的计算机上. %s",
	"此安装程序已准备就绪，可以将 %s 重新安装到您的计算机上. %s",
	"此安装程序已准备好将 %s 更新到您的计算机. %s",
	"此安装程序已准备就绪，可以从您的计算机上卸载 %s. %s",
	"准备开始安装 %s.",
	"准备重新安装 %s.",
	"准备更新 %s.",
	"准备删除 %s.",
	"单击下一步继续.",
	"此安装程序会将 %s 更新到您计算机上的版本 %s. %s",
	"此安装程序将在您的计算机上重新安装 %s 版本 %s. %s",
	"此安装程序将在您的计算机上安装 %s 版本 %s. %s",
	"或单击 卸载 按钮以卸载 %s v%s",
	"取消确认",
	"您真的要中止安装吗？",
	"正在准备...",
	"正在提取文件...",
	"正在复制文件...",
	"正在删除文件...",
	"正在注册组件...",
	"正在配置...",
	"最终...",
	"命令执行失败.",
	"请选择语言",
	"无法删除以前的版本.",
};

const char *GLanguageVietnamese[] = {
	"Tải về",
	"Gỡ cài đặt",
	"ĐỒNG Ý",
	"Đúng",
	"Không",
	"Nâng cao",
	"Trở lại",
	"Kế tiếp",
	"Hủy",
	"Chấp nhận",
	"Tiếp tục",
	"Hoàn thành",
	"Đã kết thúc",
	"Chào mừng bạn đến với trình cài đặt %s",
	"Nhập cấu hình bổ sung",
	"Chế độ cấu hình nâng cao",
	"Vui lòng định cấu hình cài đặt",
	"Thỏa thuận cấp phép",
	"Vui lòng đọc và chấp nhận thỏa thuận cấp phép",
	"Điển hình",
	"Loại cấu hình",
	"Vui lòng chọn loại cài đặt",
	"Cài đặt đã hoàn tất. %s",
	"%s đã được cài đặt lại. %s",
	"%s đã được cập nhật. %s",
	"%s đã bị xóa.",
	"Vui lòng đóng trình cài đặt để bắt đầu sử dụng %s.",
	"Đang chuẩn bị",
	"Cài đặt",
	"Cài đặt lại",
	"Đang cập nhật",
	"Đang gỡ cài đặt",
	"Vui lòng đợi trong khi cài đặt %s.",
	"Vui lòng đợi trong khi cài đặt lại %s.",
	"Vui lòng đợi trong khi cập nhật %s.",
	"Vui lòng đợi trong khi xóa %s.",
	"Nhấp vào nút Tiếp tục để bắt đầu.",
	"Trình cài đặt này đã sẵn sàng để cài đặt %s vào máy tính của bạn. %s",
	"Trình cài đặt này đã sẵn sàng để cài đặt lại %s vào máy tính của bạn. %s",
	"Trình cài đặt này đã sẵn sàng cập nhật %s vào máy tính của bạn. %s",
	"Trình cài đặt này đã sẵn sàng để gỡ cài đặt %s khỏi máy tính của bạn. %s",
	"Sẵn sàng để bắt đầu cài đặt %s.",
	"Sẵn sàng cài đặt lại %s.",
	"Sẵn sàng cập nhật %s.",
	"Sẵn sàng xóa %s.",
	"Nhấn Next để tiếp tục.",
	"Trình cài đặt này sẽ cập nhật %s lên phiên bản %s trên máy tính của bạn. %s",
	"Trình cài đặt này sẽ cài đặt lại %s phiên bản %s trên máy tính của bạn. %s",
	"Trình cài đặt này sẽ cài đặt %s phiên bản %s trên máy tính của bạn. %s",
	"Hoặc nhấp vào nút Gỡ cài đặt để gỡ cài đặt %s v%s",
	"Hủy xác nhận",
	"Bạn có thực sự muốn hủy cài đặt không?",
	"Đang chuẩn bị ...",
	"Giải nén tập tin ...",
	"Sao chép các tập tin ...",
	"Đang xóa tệp ...",
	"Đang đăng ký các thành phần ...",
	"Đang định cấu hình ...",
	"Đang hoàn thiện ...",
	"Thực thi lệnh không thành công.",
	"Vui lòng chọn ngôn ngữ",
	"Không thể xóa phiên bản trước.",
};

const char *GLanguageHindi[] = {
	"इंस्टॉल",
	"स्थापना रद्द करें",
	"ठीक है",
	"हाँ",
	"नहीं",
	"उन्नत",
	"वापस",
	"आगे",
	"रद्द करना",
	"स्वीकार करना",
	"जारी रखें",
	"समाप्त",
	"ख़त्म होना",
	"%s इंस्टॉलर में आपका स्वागत है",
	"अतिरिक्त कॉन्फ़िगरेशन दर्ज करें",
	"उन्नत कॉन्फ़िगरेशन मोड",
	"कृपया सेटिंग्स कॉन्फ़िगर करें",
	"लाइसेंस समझौता",
	"कृपया लाइसेंस समझौते को पढ़ें और स्वीकार करें",
	"ठेठ",
	"कॉन्फ़िगरेशन प्रकार",
	"कृपया संस्थापन प्रकार चुनें",
	"स्थापना समाप्त हो गई है। %s",
	"%s को पुनः स्थापित किया गया है। %s",
	"%s को अपडेट कर दिया गया है। %s",
	"%s हटा दिया गया है।",
	"कृपया %s का उपयोग शुरू करने के लिए इंस्टॉलर को बंद करें",
	"तैयार कर रहे हैं",
	"स्थापना",
	"पुनः स्थापना",
	"अपडेट कर रहा है",
	"की स्थापना रद्द",
	"कृपया %s स्थापित करते समय प्रतीक्षा करें।",
	"कृपया %s को पुन: स्थापित करते समय प्रतीक्षा करें।",
	"कृपया %s को अपडेट करते समय प्रतीक्षा करें।",
	"कृपया %s हटाते समय प्रतीक्षा करें।",
	"शुरू करने के लिए जारी रखें बटन पर क्लिक करें।",
	"यह इंस्टॉलर आपके कंप्यूटर पर %s स्थापित करने के लिए तैयार है। %s",
	"यह इंस्टॉलर आपके कंप्यूटर पर %s को फिर से स्थापित करने के लिए तैयार है।",
	"यह इंस्टॉलर आपके कंप्यूटर पर %s को अपडेट करने के लिए तैयार है।",
	"यह इंस्टॉलर आपके कंप्यूटर से %s की स्थापना रद्द करने के लिए तैयार है।",
	" %s की स्थापना शुरू करने के लिए तैयार है।",
	" %s को पुनः स्थापित करने के लिए तैयार है।",
	" %s अपडेट करने के लिए तैयार है।",
	" %s हटाने के लिए तैयार है।",
	"जारी रखने के लिए आगे दबाएँ।",
	"यह इंस्टॉलर आपके कंप्यूटर पर %s से %s तक अपडेट करेगा।",
	"यह इंस्टॉलर आपके कंप्यूटर पर %s संस्करण %s को पुनर्स्थापित करेगा। %s",
	"यह इंस्टॉलर आपके कंप्यूटर पर %s संस्करण %s स्थापित करेगा। %s",
	"या %s v%s की स्थापना रद्द करने के लिए अनइंस्टॉल बटन पर क्लिक करें",
	"पुष्टि रद्द करें",
	"क्या आप वास्तव में स्थापना रद्द करना चाहते हैं?",
	"तैयार कर रहे हैं ...",
	"फ़ाइलों को निकालना ...",
	"फ़ाइलों की प्रतिलिपि बनाई जा रही है ...",
	"फाइलें निकाल रहा है ...",
	"पंजीकरण घटक ...",
	"कॉन्फ़िगर हो रहा है ...",
	"अंतिम रूप दे रहा है ...",
	"कमांड निष्पादन विफल रहा।",
	"कृपया भाषा चुनें",
	"पिछला संस्करण निकालने में असमर्थ।",
};

const char **GLanguageTable[] = {
	GLanguageEnglish, GLanguageGermany, GLanguageFrench, GLanguageItalian, GLanguageSpanish, GLanguagePortuguese,
	GLanguageRussian, GLanguageJapanese, GLanguageKorean, GLanguageChinese, GLanguageVietnamese, GLanguageHindi
};

const char *GLanguageName[] = {
	"English", "German", "French", "Italian", "Spanish", "Portuguese", "Russian", "Japanese", "Korean", "Chinese", "Vietnamese", "Hindi"
};

const char *GLanguageNative[] = {
	"English", "Deutsche", "Française", "Italiana", "Española", "Português", "Русский", "日本人", "한국어", "中文", "Tiếng Việt", "हिंदी"
};

int GLanguageIndex = 0;
const char **GLanguageStrings = GLanguageTable[GLanguageIndex];

int GetLanguage()
{
	return GLanguageIndex;
}

void SetLanguage(int iLanguage)
{
	if(iLanguage < 0 || iLanguage >= GetLanguageCount())
		return;
	GLanguageIndex = iLanguage;
	GLanguageStrings = GLanguageTable[iLanguage];
}

bool SetLanguage(const char *lpLanguage)
{
	int iLanguage = 0;
	int nLanguage = GetLanguageCount();
	for(iLanguage = 0; iLanguage < nLanguage && strcmp(lpLanguage, GLanguageName[iLanguage]); iLanguage++);
	if(iLanguage == nLanguage)
		return false;
	SetLanguage(iLanguage);
	return true;
}

int GetLanguageCount()
{
	return sizeof(GLanguageName) / sizeof(GLanguageName[0]);
}

const char *GetLanguageName(int iLanguage, bool fNative)
{
	return fNative ? GLanguageNative[iLanguage] : GLanguageName[iLanguage];
}

const char *GetString(EString eString)
{
	return GLanguageStrings[eString];
}

